#服务key
app_key = "83f4xq9fltleq"

#服务secret
app_secret = "TBfyiak8tjrNpUE8F6Mc0lOLcX6A3yb0goZBlaYT66mghPJd6l8HFZynfgf0UhZMxtSKJJ7YB27fkhB1jCiX7L0u2Bn/9GCpw4FFPTUCfnAg4AsChzjlBoRGt3WImDJi4kOTdmVwCRNMb2caodKLc37qhw6+w34blheDU738NJs="

#服务版本号
app_version = "1.0.0"

#服务手机号
app_mobile = "15300000000"

#服务邮箱
app_email = "126@qq.com"

#服务端口
#server_network = ""


[kafkaservers]
    [kafkaservers.online]
    KafkaAddr = 127.0.0.1:9092
    KafkaUser =
    KafkaPwd =
    KafkaEnable = true
    KafkaTopic =