// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.15.8
// source: appIdentifier.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//
type AppIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appkey_       *string `protobuf:"bytes,1,opt,name=appkey_,json=appkey" json:"appkey_,omitempty"`
	Appsecret_    *string `protobuf:"bytes,2,opt,name=appsecret_,json=appsecret" json:"appsecret_,omitempty"`
	UserCount_    *int32  `protobuf:"varint,3,opt,name=userCount_,json=userCount" json:"userCount_,omitempty"`
	DeadLine_     *int64  `protobuf:"varint,4,opt,name=deadLine_,json=deadLine" json:"deadLine_,omitempty"`
	LicenseIndex_ *int64  `protobuf:"varint,5,opt,name=licenseIndex_,json=licenseIndex" json:"licenseIndex_,omitempty"`
	PackageCount_ *int32  `protobuf:"varint,6,opt,name=packageCount_,json=packageCount" json:"packageCount_,omitempty"`
	RtcUserCount_ *int32  `protobuf:"varint,7,opt,name=rtcUserCount_,json=rtcUserCount" json:"rtcUserCount_,omitempty"`
	RtcMode_      *int32  `protobuf:"varint,8,opt,name=rtcMode_,json=rtcMode" json:"rtcMode_,omitempty"`
	RtcSecret_    []byte  `protobuf:"bytes,9,opt,name=rtcSecret_,json=rtcSecret" json:"rtcSecret_,omitempty"`
}

func (x *AppIdentifier) Reset() {
	*x = AppIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appIdentifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppIdentifier) ProtoMessage() {}

func (x *AppIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_appIdentifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppIdentifier.ProtoReflect.Descriptor instead.
func (*AppIdentifier) Descriptor() ([]byte, []int) {
	return file_appIdentifier_proto_rawDescGZIP(), []int{0}
}

func (x *AppIdentifier) GetAppkey_() string {
	if x != nil && x.Appkey_ != nil {
		return *x.Appkey_
	}
	return ""
}

func (x *AppIdentifier) GetAppsecret_() string {
	if x != nil && x.Appsecret_ != nil {
		return *x.Appsecret_
	}
	return ""
}

func (x *AppIdentifier) GetUserCount_() int32 {
	if x != nil && x.UserCount_ != nil {
		return *x.UserCount_
	}
	return 0
}

func (x *AppIdentifier) GetDeadLine_() int64 {
	if x != nil && x.DeadLine_ != nil {
		return *x.DeadLine_
	}
	return 0
}

func (x *AppIdentifier) GetLicenseIndex_() int64 {
	if x != nil && x.LicenseIndex_ != nil {
		return *x.LicenseIndex_
	}
	return 0
}

func (x *AppIdentifier) GetPackageCount_() int32 {
	if x != nil && x.PackageCount_ != nil {
		return *x.PackageCount_
	}
	return 0
}

func (x *AppIdentifier) GetRtcUserCount_() int32 {
	if x != nil && x.RtcUserCount_ != nil {
		return *x.RtcUserCount_
	}
	return 0
}

func (x *AppIdentifier) GetRtcMode_() int32 {
	if x != nil && x.RtcMode_ != nil {
		return *x.RtcMode_
	}
	return 0
}

func (x *AppIdentifier) GetRtcSecret_() []byte {
	if x != nil {
		return x.RtcSecret_
	}
	return nil
}

//
type License struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NaviHost_    *string `protobuf:"bytes,1,opt,name=naviHost_,json=naviHost" json:"naviHost_,omitempty"`
	ApiHost_     *string `protobuf:"bytes,2,opt,name=apiHost_,json=apiHost" json:"apiHost_,omitempty"`
	IsClustered_ *bool   `protobuf:"varint,3,opt,name=isClustered_,json=isClustered" json:"isClustered_,omitempty"`
	UserCount_   *int32  `protobuf:"varint,4,opt,name=userCount_,json=userCount" json:"userCount_,omitempty"`
	AppKeyCode_  *int32  `protobuf:"varint,5,opt,name=appKeyCode_,json=appKeyCode" json:"appKeyCode_,omitempty"`
	DeadLine_    *int64  `protobuf:"varint,6,opt,name=deadLine_,json=deadLine" json:"deadLine_,omitempty"`
	CreatedTime_ *int64  `protobuf:"varint,7,opt,name=createdTime_,json=createdTime" json:"createdTime_,omitempty"`
	Desc_        *string `protobuf:"bytes,8,opt,name=desc_,json=desc" json:"desc_,omitempty"`
	EncodeKey_   []byte  `protobuf:"bytes,9,opt,name=encodeKey_,json=encodeKey" json:"encodeKey_,omitempty"`
	Index_       *int64  `protobuf:"varint,10,opt,name=index_,json=index" json:"index_,omitempty"`
}

func (x *License) Reset() {
	*x = License{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appIdentifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *License) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*License) ProtoMessage() {}

func (x *License) ProtoReflect() protoreflect.Message {
	mi := &file_appIdentifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use License.ProtoReflect.Descriptor instead.
func (*License) Descriptor() ([]byte, []int) {
	return file_appIdentifier_proto_rawDescGZIP(), []int{1}
}

func (x *License) GetNaviHost_() string {
	if x != nil && x.NaviHost_ != nil {
		return *x.NaviHost_
	}
	return ""
}

func (x *License) GetApiHost_() string {
	if x != nil && x.ApiHost_ != nil {
		return *x.ApiHost_
	}
	return ""
}

func (x *License) GetIsClustered_() bool {
	if x != nil && x.IsClustered_ != nil {
		return *x.IsClustered_
	}
	return false
}

func (x *License) GetUserCount_() int32 {
	if x != nil && x.UserCount_ != nil {
		return *x.UserCount_
	}
	return 0
}

func (x *License) GetAppKeyCode_() int32 {
	if x != nil && x.AppKeyCode_ != nil {
		return *x.AppKeyCode_
	}
	return 0
}

func (x *License) GetDeadLine_() int64 {
	if x != nil && x.DeadLine_ != nil {
		return *x.DeadLine_
	}
	return 0
}

func (x *License) GetCreatedTime_() int64 {
	if x != nil && x.CreatedTime_ != nil {
		return *x.CreatedTime_
	}
	return 0
}

func (x *License) GetDesc_() string {
	if x != nil && x.Desc_ != nil {
		return *x.Desc_
	}
	return ""
}

func (x *License) GetEncodeKey_() []byte {
	if x != nil {
		return x.EncodeKey_
	}
	return nil
}

func (x *License) GetIndex_() int64 {
	if x != nil && x.Index_ != nil {
		return *x.Index_
	}
	return 0
}

//
type ServerLicense struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appkey      *string `protobuf:"bytes,1,opt,name=appkey" json:"appkey,omitempty"`
	Appsecret   *string `protobuf:"bytes,2,opt,name=appsecret" json:"appsecret,omitempty"`
	DeadLine    *int64  `protobuf:"varint,3,opt,name=deadLine" json:"deadLine,omitempty"`
	CreatedTime *int64  `protobuf:"varint,4,opt,name=createdTime" json:"createdTime,omitempty"`
	Network     *string `protobuf:"bytes,5,opt,name=network" json:"network,omitempty"`
}

func (x *ServerLicense) Reset() {
	*x = ServerLicense{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appIdentifier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerLicense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLicense) ProtoMessage() {}

func (x *ServerLicense) ProtoReflect() protoreflect.Message {
	mi := &file_appIdentifier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLicense.ProtoReflect.Descriptor instead.
func (*ServerLicense) Descriptor() ([]byte, []int) {
	return file_appIdentifier_proto_rawDescGZIP(), []int{2}
}

func (x *ServerLicense) GetAppkey() string {
	if x != nil && x.Appkey != nil {
		return *x.Appkey
	}
	return ""
}

func (x *ServerLicense) GetAppsecret() string {
	if x != nil && x.Appsecret != nil {
		return *x.Appsecret
	}
	return ""
}

func (x *ServerLicense) GetDeadLine() int64 {
	if x != nil && x.DeadLine != nil {
		return *x.DeadLine
	}
	return 0
}

func (x *ServerLicense) GetCreatedTime() int64 {
	if x != nil && x.CreatedTime != nil {
		return *x.CreatedTime
	}
	return 0
}

func (x *ServerLicense) GetNetwork() string {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return ""
}

var File_appIdentifier_proto protoreflect.FileDescriptor

var file_appIdentifier_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x02, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6b, 0x65,
	0x79, 0x5f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x5f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6c,
	0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x74, 0x63, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x74,
	0x63, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x74,
	0x63, 0x4d, 0x6f, 0x64, 0x65, 0x5f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x74,
	0x63, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x74, 0x63, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x5f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x74, 0x63, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x22, 0xaf, 0x02, 0x0a, 0x07, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x61, 0x76, 0x69, 0x48, 0x6f, 0x73, 0x74, 0x5f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x61, 0x76, 0x69, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x70, 0x69, 0x48, 0x6f, 0x73, 0x74, 0x5f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x70, 0x69, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x69, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70,
	0x70, 0x4b, 0x65, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x61, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x65, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x5f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x64, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x64,
	0x65, 0x73, 0x63, 0x5f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x5f, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x15, 0x0a, 0x06, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x9d, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
}

var (
	file_appIdentifier_proto_rawDescOnce sync.Once
	file_appIdentifier_proto_rawDescData = file_appIdentifier_proto_rawDesc
)

func file_appIdentifier_proto_rawDescGZIP() []byte {
	file_appIdentifier_proto_rawDescOnce.Do(func() {
		file_appIdentifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_appIdentifier_proto_rawDescData)
	})
	return file_appIdentifier_proto_rawDescData
}

var file_appIdentifier_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_appIdentifier_proto_goTypes = []interface{}{
	(*AppIdentifier)(nil), // 0: AppIdentifier
	(*License)(nil),       // 1: License
	(*ServerLicense)(nil), // 2: ServerLicense
}
var file_appIdentifier_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_appIdentifier_proto_init() }
func file_appIdentifier_proto_init() {
	if File_appIdentifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_appIdentifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appIdentifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*License); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appIdentifier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerLicense); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_appIdentifier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_appIdentifier_proto_goTypes,
		DependencyIndexes: file_appIdentifier_proto_depIdxs,
		MessageInfos:      file_appIdentifier_proto_msgTypes,
	}.Build()
	File_appIdentifier_proto = out.File
	file_appIdentifier_proto_rawDesc = nil
	file_appIdentifier_proto_goTypes = nil
	file_appIdentifier_proto_depIdxs = nil
}
